### ISSUE TITLE
Systemd script not working

### ISSUE THREAD

**Issue by samuelebistoletti** [johnhamelink/exrm-deb#30]
Systemd script is not working when trying to start the application packaged with distillery.

I got this error:
Active: failed (Result: exit-code) since lun 2017-01-23 12:10:53 CET; 3min 17s left
Process: 593 ExecStop=/opt/app/bin/app stop (code=exited, status=1/FAILURE)
Process: 487 ExecStart=/opt/app/bin/app start (code=exited, status=0/SUCCESS)
Main PID: 591 (code=exited, status=0/SUCCESS)

If I try to start the app with: /opt/app/bin/app start, it works, so the problem must be systemd script itself.

**Comment by johnhamelink** [comment]
Hey there :)

I looks from your logs like the app did start up when systemd executed the command under ExecStart - can you verify that when you run "start <app name>" manually it doesn't start up? Could you should the logs for that as well?

**Comment by samuelebistoletti** [comment]
When I start the app manually it starts, it responds to /opt/app/bin/app ping, then I stop with /opt/app/bin/app stop, and if i try to start it with systemd i got the failure. The app in this case is not starting, i can't reach it or see a pid.

**Comment by johnhamelink** [comment]
@samuelebistoletti thank you for that PR! I have merged it and I will deploy a release as soon as I am able to.
